const municipios = [
    'Abasolo',
    'Agualeguas',
    'Allende',
    'Anahuac',
    'Apodaca',
    'Aramberri',
    'Bustamante',
    'Cadereyta Jiménez',
    'Cerralvo',
    'Ciénega de Flores',
    'China',
    'Doctor Arroyo',
    'Doctor Coss',
    'Doctor González',
    'El Carmen',
    'Galeana',
    'García',
    'General Bravo',
    'General Escobedo',
    'General Terán',
    'General Treviño',
    'General Zaragoza',
    'General Zuazua',
    'Guadalupe',
    'Hidalgo',
    'Higueras',
    'Hualahuises',
    'Iturbide',
    'Juárez',
    'Lampazos de Naranjo',
    'Linares',
    'Los Aldamas',
    'Los Herreras',
    'Los Ramones',
    'Marín',
    'Melchor Ocampo',
    'Mier y Noriega',
    'Mina',
    'Montemorelos',
    'Monterrey',
    'Parás',
    'Pesquería',
    'Rayones',
    'Sabinas Hidalgo',
    'Salinas Victoria',
    'San Nicolás de los Garza',
    'San Pedro Garza García',
    'Santa Catarina',
    'Santiago',
    'Vallecillo',
    'Villaldama'
]

export default municipios