const puestos = [
    'Director General',
    'Director',
    'Gerente',
    'Recursos Humanos',
    'Jefe de Departamento',
    'Secretaria/Auxiliar',
    'Analista',
    'Ayudante/Peaton',
    'Trabajador en agricultura',
    'Trabajador en educación',
    'Trabajador en arte',
    'Trabajador en espectaculo',
    'Trabajador en deporte',
    'Trabajador en administración',
    'Seguridad/Vigilancia',
    'Trabajo de Ventas: Comisionista',
    'Trabajo de Ventas: Vendedor',
    'Servicios personales',
    'Servicios domesticos',
    'Servicios de protección',
    'Coach/Capacitador',
    'Coach deportivo',
    'Pedagogia',
    'Andragogia',
    'Enfermeria',
    'Comercio',
    'Cuidador de adultos mayores',
    'Terapia de rehabilitación',
    'Mediación',
    'Técnico en maquinas/herramientas',
    'Otros'
]

export default puestos